- name: Include RedHat-specific tasks
  include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Include Debian/Ubuntu-specific tasks
  include_tasks: debian.yml
  when: ansible_os_family == "Debian"
