---
- name: Install Java (OpenJDK 17) on RedHat
  yum:
    name: java-17-openjdk
    state: present

- name: Import Elasticsearch GPG key
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Download Elasticsearch RPM package
  get_url:
    url: "{{ elasticsearch_package_url_centos }}"
    dest: /tmp/elasticsearch.rpm

- name: Install Elasticsearch using RPM
  yum:
    name: /tmp/elasticsearch.rpm
    state: present

- name: Ensure Elasticsearch data directory exists
  file:
    path: /usr/share/elasticsearch/data
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: '0755'

- name: Configure Elasticsearch with templated config
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: '0640'
  notify: restart elasticsearch

- name: Enable and start Elasticsearch service
  systemd:
    name: elasticsearch
    state: started
    enabled: true